# Generated by Django 5.0.7 on 2025-09-30 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign_type', models.CharField(choices=[('bulk_calls', 'Bulk Calls'), ('drip_campaign', 'Drip Campaign'), ('appointment_reminders', 'Appointment Reminders'), ('follow_up', 'Follow Up Campaign'), ('survey', 'Survey Campaign')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('allowed_calling_hours_start', models.TimeField(default='09:00:00')),
                ('allowed_calling_hours_end', models.TimeField(default='18:00:00')),
                ('allowed_days_of_week', models.JSONField(default=list)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('max_calls_per_hour', models.IntegerField(default=10)),
                ('max_calls_per_day', models.IntegerField(default=100)),
                ('total_contacts', models.IntegerField(default=0)),
                ('completed_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('failed_calls', models.IntegerField(default=0)),
                ('campaign_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.calltemplate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('opted_out', 'Opted Out')], default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('call_result', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contact')),
            ],
            options={
                'db_table': 'campaign_contacts',
                'ordering': ['scheduled_time', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_contacts',
            field=models.ManyToManyField(blank=True, through='scheduling.CampaignContact', to='crm.contact'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('schedule_type', models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring'), ('conditional', 'Conditional')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('task_name', models.CharField(max_length=100)),
                ('task_args', models.JSONField(blank=True, default=list)),
                ('task_kwargs', models.JSONField(blank=True, default=dict)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('recurrence_type', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20, null=True)),
                ('recurrence_interval', models.IntegerField(default=1)),
                ('recurrence_rule', models.CharField(blank=True, max_length=500, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('max_runs', models.IntegerField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['next_run', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('retried', 'Retried')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduling.schedule')),
            ],
            options={
                'db_table': 'schedule_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallTimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('booking_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slots', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.campaign')),
            ],
            options={
                'db_table': 'call_time_slots',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time'], name='call_time_s_start_t_1f6785_idx'), models.Index(fields=['status'], name='call_time_s_status_9b06e4_idx'), models.Index(fields=['assigned_agent'], name='call_time_s_assigne_7d4ab0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['campaign', 'status'], name='campaign_co_campaig_61c1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['scheduled_time'], name='campaign_co_schedul_f5dd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['status'], name='campaign_co_status_4f5dec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncontact',
            unique_together={('campaign', 'contact')},
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaigns_status_a03570_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='campaigns_campaig_b4a9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='campaigns_start_d_5c2c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_by'], name='campaigns_created_a7f3be_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='schedules_status_0e1604_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['next_run'], name='schedules_next_ru_4d7a31_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['task_name'], name='schedules_task_na_3b6384_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleexecution',
            index=models.Index(fields=['schedule', 'status'], name='schedule_ex_schedul_d15e89_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleexecution',
            index=models.Index(fields=['started_at'], name='schedule_ex_started_d79642_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleexecution',
            index=models.Index(fields=['celery_task_id'], name='schedule_ex_celery__2770ac_idx'),
        ),
    ]
