# Generated by Django 5.0.7 on 2025-09-30 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twilio_call_sid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('call_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('busy', 'Busy'), ('no_answer', 'No Answer'), ('voicemail', 'Voicemail')], default='initiated', max_length=20)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('ai_conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('recording_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('call_metadata', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm.contact')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_type', models.CharField(choices=[('ai', 'AI Assistant'), ('human', 'Human'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='calls.call')),
            ],
            options={
                'db_table': 'call_conversations',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CallTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('sales', 'Sales Call'), ('support', 'Customer Support'), ('survey', 'Survey'), ('appointment', 'Appointment Booking'), ('follow_up', 'Follow Up'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('initial_greeting', models.TextField()),
                ('conversation_flow', models.JSONField(default=dict)),
                ('closing_message', models.TextField()),
                ('ai_voice', models.CharField(default='alloy', max_length=50)),
                ('ai_temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(default=3)),
                ('attempt_count', models.IntegerField(default=0)),
                ('call_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_notes', models.TextField(blank=True, null=True)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.call')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('call_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.calltemplate')),
            ],
            options={
                'db_table': 'call_queue',
                'ordering': ['priority', 'scheduled_time', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['twilio_call_sid'], name='calls_twilio__2d72bf_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['contact'], name='calls_contact_8fe0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_type'], name='calls_call_ty_2dda79_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status'], name='calls_status_de57eb_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['created_at'], name='calls_created_e2f5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='callqueue',
            index=models.Index(fields=['status'], name='call_queue_status_e9a06f_idx'),
        ),
        migrations.AddIndex(
            model_name='callqueue',
            index=models.Index(fields=['priority'], name='call_queue_priorit_8c926e_idx'),
        ),
        migrations.AddIndex(
            model_name='callqueue',
            index=models.Index(fields=['scheduled_time'], name='call_queue_schedul_c0e57e_idx'),
        ),
        migrations.AddIndex(
            model_name='callqueue',
            index=models.Index(fields=['contact'], name='call_queue_contact_2952ef_idx'),
        ),
    ]
